services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - main_service/.dev.env
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:17.3
    container_name: postgres
    restart: always

    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - main_service/.dev.env

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # Порт для AMQP
      - "15672:15672"  # Порт для веба
    env_file:
      - main_service/.dev.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      - postgres
      - rabbitmq
      - minio
    links:
      - "postgres:postgres"
      - "rabbitmq:rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    build:
      context: main_service
      dockerfile: ./Dockerfile
    env_file:
      - main_service/.dev.env
    ports:
      - 8000:8080

  parser:
    depends_on:
      - backend
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    build:
      context: parser
      dockerfile: ./Dockerfile
    env_file:
      - main_service/.dev.env

volumes:
  postgres-data:
  rabbitmq_data:
  minio_data:
