services:
  postgres:
    image: postgres:17.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - main_service/.env

  backend:
    links:
      - "postgres:postgres"
    container_name: backend-app
    restart: always
    build: main_service
    env_file:
      - main_service/.env
    ports:
      - 5000:5000

  adminer:
    links:
      - "postgres:postgres"
    container_name: adminer
    image: adminer
    restart: always
    environment:
      host: localhost
    ports:
      - 8080:8080

volumes:
  postgres-data: