- name: Deploy on single node
  hosts: master
  become: true

  vars_files:
    - ./vars/secrets.yaml
    - ./vars/deploy.yaml

  roles:
    - geerlingguy.docker

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: web
        password: "{{ user.password | password_hash('sha512') }}"
        state: present
        createhome: true
        groups:
          - docker
    - name: Create project root
      ansible.builtin.file:
        path: /var/www/events
        state: directory
        owner: web
        group: web
        mode: "0777"
    - name: Copy infra compose
      ansible.builtin.copy:
        src: ./docker-compose.infra.yaml
        dest: /var/www/events/docker-compose.infra.yaml
        owner: web
        group: web
        mode: "0777"
    - name: Create caddy dir
      ansible.builtin.file:
        path: /var/www/events/caddy/conf
        state: directory
        owner: web
        group: web
        mode: "0777"
    - name: Copy caddy config
      ansible.builtin.template:
        src: ./caddy/conf/Caddyfile.j2
        dest: /var/www/events/caddy/conf/Caddyfile
        owner: web
        group: web
        mode: "0777"
    - name: Copy cleanup script
      ansible.builtin.copy:
        src: ./cleanup.sh
        dest: /var/www/events/cleanup.sh
        owner: web
        group: web
        mode: "0777"
    - name: Run infra compose
      community.docker.docker_compose_v2:
        project_src: /var/www/events
        pull: always
        remove_orphans: true
        files:
          - docker-compose.infra.yaml
