include:
  - docker-compose.infra.yaml

services:
  main-service:
    image: ${MAIN_SERVICE_IMAGE}
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres
      - caddy
      - rabbit
      - minio
    env_file:
      - ./main-service.env
  main-service-migrations:
    image: ${MAIN_SERVICE_MIGRATIONS_IMAGE}
    restart: on-failure:3
    networks:
      - postgres
    env_file:
      - ./main-service.env
    depends_on:
      - postgres

  parser:
    image: ${PARSER_IMAGE}
    restart: always
    networks:
      - rabbit
      - minio
    env_file:
      - ./parser.env
  
  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - caddy
