from enum import Enum


class PermissionsEnum(Enum):
    # Event region
    CAN_READ_EVENT = "CAN_READ_EVENT"
    CAN_UPDATE_EVENT = "CAN_UPDATE_EVENT"
    CAN_DELETE_EVENT = "CAN_DELETE_EVENT"
    CAN_CREATE_EVENT = "CAN_CREATE_EVENT"
    # Attachment region
    CAN_READ_ATTACHMENT = "CAN_READ_ATTACHMENT"
    CAN_CREATE_ATTACHMENT = "CAN_CREATE_ATTACHMENT"
    CAN_DELETE_ATTACHMENT = "CAN_DELETE_ATTACHMENT"
    CAN_UPDATE_ATTACHMENT = "CAN_UPDATE_ATTACHMENT"
