from enum import Enum


class PermissionsEnum(Enum):
    # Event region
    CAN_READ_EVENT = "CAN_READ_EVENT"
    CAN_UPDATE_EVENT = "CAN_UPDATE_EVENT"
    CAN_DELETE_EVENT = "CAN_DELETE_EVENT"
    CAN_CREATE_EVENT = "CAN_CREATE_EVENT"
    # Organization
    CAN_CREATE_ORGANIZATION = "CAN_CREATE_ORGANIZATION"
    CAN_DELETE_ORGANIZATION = "CAN_DELETE_ORGANIZATION"
    CAN_UPDATE_ORGANIZATION = "CAN_UPDATE_ORGANIZATION"
    CAN_SEND_ORGANIZATION_LINK = "CAN_SEND_ORGANIZATION_LINK"
