from enum import Enum


class PermissionsEnum(Enum):
    # Event region
    CAN_READ_EVENT = "CAN_READ_EVENT"
    CAN_UPDATE_EVENT = "CAN_UPDATE_EVENT"
    CAN_DELETE_EVENT = "CAN_DELETE_EVENT"
    CAN_CREATE_EVENT = "CAN_CREATE_EVENT"
    # Notification region
    CAN_READ_NOTIFICATION = "CAN_READ_NOTIFICATION"
    CAN_UPDATE_NOTIFICATION = "CAN_UPDATE_NOTIFICATION"
    CAN_DELETE_NOTIFICATION = "CAN_DELETE_NOTIFICATION"
    CAN_CREATE_NOTIFICATION = "CAN_CREATE_NOTIFICATION"
