"""update event model

Revision ID: 020fdbf73f0e
Revises: 37a39c573f50
Create Date: 2025-03-30 00:59:47.697069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "020fdbf73f0e"
down_revision: Union[str, None] = "37a39c573f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "events",
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "start_date")
    op.drop_column("events", "end_date")
    # ### end Alembic commands ###
