"""Merge migrations & update notification

Revision ID: d692b7a44694
Revises: 5be9adf87828
Create Date: 2025-05-09 17:52:05.762520

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d692b7a44694"
down_revision: Union[str, None] = "5be9adf87828"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("event_id", sa.Integer(), nullable=False))
    op.add_column("notifications", sa.Column("send_date", sa.Date(), nullable=False))
    op.create_unique_constraint(
        "unique_notification",
        "notifications",
        ["event_id", "recipient_id", "send_date"],
    )
    op.create_foreign_key(
        op.f("fk_notifications_event_id_events"),
        "notifications",
        "events",
        ["event_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notifications_event_id_events"), "notifications", type_="foreignkey"
    )
    op.drop_constraint("unique_notification", "notifications", type_="unique")
    op.drop_column("notifications", "send_date")
    op.drop_column("notifications", "event_id")
    # ### end Alembic commands ###
