"""Add mails model

Revision ID: eb47cacc5420
Revises: 53ffba81937f
Create Date: 2025-04-28 09:34:25.456319

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "eb47cacc5420"
down_revision: Union[str, None] = "53ffba81937f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
