"""Add cascade or set null on organization delete

Revision ID: f3975c35e33d
Revises: cbfd6db63e43
Create Date: 2025-05-05 22:24:05.019654

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3975c35e33d"
down_revision: Union[str, None] = "cbfd6db63e43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_attachments_event_id_events", "attachments", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_attachments_mail_id_mails", "attachments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_attachments_event_id_events"),
        "attachments",
        "events",
        ["event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_attachments_mail_id_mails"),
        "attachments",
        "mails",
        ["mail_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "fk_events_organization_id_organizations", "events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_events_organization_id_organizations"),
        "events",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("fk_mails_event_id_events", "mails", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_mails_event_id_events"),
        "mails",
        "events",
        ["event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "fk_notifications_recipient_id_users",
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_notifications_recipient_id_users"),
        "notifications",
        "users",
        ["recipient_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_user_organization_role_organization_id_organizations",
        "user_organization_role",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_organization_role_organization_id_organizations"),
        "user_organization_role",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_organization_role_organization_id_organizations"),
        "user_organization_role",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_organization_role_organization_id_organizations",
        "user_organization_role",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_notifications_recipient_id_users"),
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_notifications_recipient_id_users",
        "notifications",
        "users",
        ["recipient_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_mails_event_id_events"), "mails", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_mails_event_id_events", "mails", "events", ["event_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_events_organization_id_organizations"),
        "events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_events_organization_id_organizations",
        "events",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_attachments_mail_id_mails"), "attachments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_attachments_event_id_events"),
        "attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_attachments_mail_id_mails",
        "attachments",
        "mails",
        ["mail_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_attachments_event_id_events",
        "attachments",
        "events",
        ["event_id"],
        ["id"],
    )
    # ### end Alembic commands ###
