"""change events model

Revision ID: 7caa48a1bab4
Revises: 571bb16d648b
Create Date: 2025-04-30 19:44:47.616789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7caa48a1bab4"
down_revision: Union[str, None] = "571bb16d648b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum").create(
        op.get_bind()
    )
    sa.Enum("HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum").create(
        op.get_bind()
    )
    op.alter_column(
        "events",
        "type",
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM(
            "HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum"
        ),
        existing_nullable=False,
        postgresql_using='type::"EventTypeEnum"',
    )
    op.alter_column(
        "events",
        "format",
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM(
            "ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum"
        ),
        existing_nullable=False,
        postgresql_using='format::"EventFormatEnum"',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "format",
        existing_type=postgresql.ENUM(
            "ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "type",
        existing_type=postgresql.ENUM(
            "HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    sa.Enum("HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum").drop(
        op.get_bind()
    )
    sa.Enum("ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
