"""change events model

Revision ID: 44282ddc28ef
Revises: c39941136d1e
Create Date: 2025-04-30 19:30:11.532573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44282ddc28ef'
down_revision: Union[str, None] = 'c39941136d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('HACKATHON', 'CONFERENCE', 'CONTEST', 'OTHER', name='EventTypeEnum'),
               existing_nullable=False,
               postgresql_using='type::EventTypeEnum')
    op.alter_column('events', 'format',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('ONLINE', 'OFFLINE', 'MIXED', 'OTHER', name='EventFormatEnum'),
               existing_nullable=False,
               postgresql_using='format::EventFormatEnum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'format',
               existing_type=postgresql.ENUM('ONLINE', 'OFFLINE', 'MIXED', 'OTHER', name='EventFormatEnum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('events', 'type',
               existing_type=postgresql.ENUM('HACKATHON', 'CONFERENCE', 'CONTEST', 'OTHER', name='EventTypeEnum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
