"""апдейт енама

Revision ID: 329fcc491e3c
Revises: bac716464e91
Create Date: 2025-05-27 00:14:46.999961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "329fcc491e3c"
down_revision: Union[str, None] = "bac716464e91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "format")
    op.drop_column("notifications", "status")
    sa.Enum("SENT", "UNSENT", name="NotificationStatusEnum").drop(op.get_bind())
    sa.Enum("HTML", "RAW_TEXT", name="NotificationFormatEnum").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("HTML", "RAW_TEXT", name="NotificationFormatEnum").create(op.get_bind())
    sa.Enum("SENT", "UNSENT", name="NotificationStatusEnum").create(op.get_bind())
    op.add_column(
        "notifications",
        sa.Column(
            "status",
            postgresql.ENUM(
                "SENT", "UNSENT", name="NotificationStatusEnum", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "format",
            postgresql.ENUM(
                "HTML", "RAW_TEXT", name="NotificationFormatEnum", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
