"""Add calendar_uuid

Revision ID: 5667a261d432
Revises: bac716464e91
Create Date: 2025-05-26 08:32:57.055500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "5667a261d432"
down_revision: Union[str, None] = "bac716464e91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_settings", sa.Column("calendar_uuid", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "calendar_uuid")
    # ### end Alembic commands ###
