"""Add events model

Revision ID: 53ffba81937f
Revises: 846b387a99f0
Create Date: 2025-04-28 09:33:51.698641

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53ffba81937f"
down_revision: Union[str, None] = "846b387a99f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_events_organization_id_users"),
        "events",
        "users",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_events_organization_id_users"), "events", type_="foreignkey"
    )
    # ### end Alembic commands ###
