"""Add attachmetns  model

Revision ID: fcb766c9c616
Revises: eb47cacc5420
Create Date: 2025-04-28 09:34:59.961988

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fcb766c9c616"
down_revision: Union[str, None] = "eb47cacc5420"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
