"""added_validation_from_mail

Revision ID: b61c21669c0a
Revises: 4f9842da485d
Create Date: 2025-05-19 19:30:54.636236

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "b61c21669c0a"
down_revision: Union[str, None] = "4f9842da485d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activation_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_activation_tokens_user_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_activation_tokens")),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="NotificationFormatEnum",
        new_values=["HTML", "RAW_TEXT", "MARKDOWN"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="notifications",
                column_name="format",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="NotificationStatusEnum",
        new_values=["UNSENT", "SENT", "FAILED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="notifications",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="NotificationStatusEnum",
        new_values=["SENT", "UNSENT"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="notifications",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="NotificationFormatEnum",
        new_values=["HTML", "RAW_TEXT"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="notifications",
                column_name="format",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_table("user_activation_tokens")
    # ### end Alembic commands ###
