"""Fix fk constraint on event model

Revision ID: b49a8f1e34e1
Revises: 7caa48a1bab4
Create Date: 2025-05-01 20:36:49.872418

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b49a8f1e34e1"
down_revision: Union[str, None] = "7caa48a1bab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_events_organization_id_users", "events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_events_organization_id_organizations"),
        "events",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_events_organization_id_organizations"),
        "events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_events_organization_id_users",
        "events",
        "users",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###
