"""Add OrganizationToken model

Revision ID: cbfd6db63e43
Revises: da1992e6fa8d
Create Date: 2025-05-05 20:31:04.674325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbfd6db63e43"
down_revision: Union[str, None] = "da1992e6fa8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("used_by", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_organization_tokens_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
            name=op.f("fk_organization_tokens_used_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_tokens")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_tokens")
    # ### end Alembic commands ###
