"""change events model

Revision ID: c39941136d1e
Revises: 571bb16d648b
Create Date: 2025-04-30 19:08:32.082596

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c39941136d1e"
down_revision: Union[str, None] = "571bb16d648b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum"
    ).create(op.get_bind())
    sa.Enum(
        "HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum"
    ).create(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "HACKATHON", "CONFERENCE", "CONTEST", "OTHER", name="EventTypeEnum"
    ).drop(op.get_bind())
    sa.Enum("ONLINE", "OFFLINE", "MIXED", "OTHER", name="EventFormatEnum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
