"""add mail model

Revision ID: ba91cfce99d6
Revises: 020fdbf73f0e
Create Date: 2025-03-31 22:40:33.302491

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba91cfce99d6"
down_revision: Union[str, None] = "020fdbf73f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("UNPROCESSED", "PROCESSED", name="MailStateEnum").create(
        op.get_bind()
    )
    op.create_table(
        "mails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("raw_content", sa.LargeBinary(), nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "UNPROCESSED",
                "PROCESSED",
                name="MailStateEnum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_mails_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mails")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mails")
    sa.Enum("UNPROCESSED", "PROCESSED", name="MailStateEnum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
