"""Update Event & Mail model

Revision ID: be19b0601ab8
Revises: 7b57f0b5866c
Create Date: 2025-04-18 18:34:40.348222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be19b0601ab8"
down_revision: Union[str, None] = "7b57f0b5866c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mails", sa.Column("received_date", sa.Date(), nullable=False)
    )
    op.add_column(
        "mails",
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mails", "retry_after")
    op.drop_column("mails", "received_date")
    # ### end Alembic commands ###
