"""Add Attachments model

Revision ID: d9f9b28821e5
Revises: 56125c271090
Create Date: 2025-04-23 16:32:33.618404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9f9b28821e5"
down_revision: Union[str, None] = "56125c271090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("mail_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mail_id is not null or event_id is not null",
            name=op.f("ck_attachments_attachment_links"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_attachments_event_id_events"),
        ),
        sa.ForeignKeyConstraint(
            ["mail_id"], ["mails.id"], name=op.f("fk_attachments_mail_id_mails")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attachments")
    # ### end Alembic commands ###
