"""Update Event model

Revision ID: fe1efcffce52
Revises: 3f3871bf56ee
Create Date: 2025-04-13 23:21:31.091542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1efcffce52'
down_revision: Union[str, None] = '3f3871bf56ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('type', sa.String(), nullable=False))
    op.add_column('events', sa.Column('format', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'format')
    op.drop_column('events', 'type')
    # ### end Alembic commands ###
