export const MULTI_DAY_EVENT_HEIGHT = 20;
export const DATE_NUMBER_AREA_HEIGHT = 30;
export const MULTI_DAY_EVENT_VERTICAL_GAP = 2;
export const ESTIMATED_DAY_NAMES_HEADER_HEIGHT = 30;
export const ESTIMATED_SINGLE_EVENT_HEIGHT = 18;
export const ESTIMATED_MORE_LINK_HEIGHT = 16;
