user:
  password: # пароль от юзера, который будет запускать докер

postgres:
  # данные для создания админа в postgres
  db: # имя бд
  user: # имя юзера бд
  password: # пароль юзера бд

rabbit:
  # данные для создания админа в rabbitmq
  user: # имя юзера rabbitmq
  password: # пароль юзера rabbitmq

minio:
  # данные для создания админа в minio
  user: # имя админа minio
  password: # пароль админа minio

parser:
  openai_api_key: # токен для openrouter

main_service:
  secret: # секрет для jwt и для паролей
  imap:
    server: # imap сервер для парсинга почты
    username: # imap username или адрес почты
    password: # пароль для imap
  smtp:
    # username и password берётся от imap
    server: # smtp сервер для отправки уведомлений
    port: # smtp порт
  tg_token: # токен для telegram-бота с уведомлениями
  admin:
    username: # почта для админа с ролью SUPER_OWNER
    password: # пароль для админа
